// <auto-generated />
using System;
using Helluz.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helluz.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251101221717_nullablefechas")]
    partial class nullablefechas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Helluz.Models.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlumno"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NroEmergencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlumno");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Helluz.Models.AlumnoHorario", b =>
                {
                    b.Property<int>("IdAlumnoHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlumnoHorario"));

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdHorario")
                        .HasColumnType("int");

                    b.HasKey("IdAlumnoHorario");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdHorario");

                    b.ToTable("AlumnoHorarios");
                });

            modelBuilder.Entity("Helluz.Models.AsistenciaAlumno", b =>
                {
                    b.Property<int>("IdAsistenciaAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistenciaAlumno"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.HasKey("IdAsistenciaAlumno");

                    b.HasIndex("IdAlumno");

                    b.ToTable("AsistenciaAlumnos");
                });

            modelBuilder.Entity("Helluz.Models.AsistenciaInstructor", b =>
                {
                    b.Property<int>("IdAsistenciaInstructor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistenciaInstructor"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int?>("HorarioIdHorario")
                        .HasColumnType("int");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int");

                    b.HasKey("IdAsistenciaInstructor");

                    b.HasIndex("HorarioIdHorario");

                    b.HasIndex("IdInstructor");

                    b.ToTable("AsistenciaInstructor");
                });

            modelBuilder.Entity("Helluz.Models.Disciplina", b =>
                {
                    b.Property<int>("IdDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDisciplina"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreDisciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDisciplina");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("Helluz.Models.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int?>("IdDicsiplina")
                        .HasColumnType("int");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int");

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdDicsiplina");

                    b.HasIndex("IdInstructor");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("Helluz.Models.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdMembresia")
                        .HasColumnType("int");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<int>("NroPermisos")
                        .HasColumnType("int");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdMembresia");

                    b.ToTable("Inscripcions");
                });

            modelBuilder.Entity("Helluz.Models.Instructor", b =>
                {
                    b.Property<int>("IdInstructor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstructor"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Celular")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdInstructor");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Helluz.Models.Membresia", b =>
                {
                    b.Property<int>("IdMembresia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMembresia"));

                    b.Property<float>("Costo")
                        .HasColumnType("real");

                    b.Property<bool>("EsPromocion")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActivo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInactivo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nro_sesiones")
                        .HasColumnType("int");

                    b.HasKey("IdMembresia");

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("Helluz.Models.TokenQr", b =>
                {
                    b.Property<int>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdToken"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaGeneracion")
                        .HasColumnType("date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdToken");

                    b.ToTable("TokenQrs");
                });

            modelBuilder.Entity("Helluz.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estados")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Helluz.Models.AlumnoHorario", b =>
                {
                    b.HasOne("Helluz.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helluz.Models.Horario", "Horario")
                        .WithMany("AlumnoHorarios")
                        .HasForeignKey("IdHorario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("Helluz.Models.AsistenciaAlumno", b =>
                {
                    b.HasOne("Helluz.Models.Alumno", "Alumno")
                        .WithMany("Asistencia_Alumnos")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Helluz.Models.AsistenciaInstructor", b =>
                {
                    b.HasOne("Helluz.Models.Horario", null)
                        .WithMany("AsistenciaInstructors")
                        .HasForeignKey("HorarioIdHorario");

                    b.HasOne("Helluz.Models.Instructor", "Instructor")
                        .WithMany("AsistenciaInstructors")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Helluz.Models.Horario", b =>
                {
                    b.HasOne("Helluz.Models.Disciplina", "Disciplina")
                        .WithMany("Horarios")
                        .HasForeignKey("IdDicsiplina");

                    b.HasOne("Helluz.Models.Instructor", "Instructor")
                        .WithMany("Horarios")
                        .HasForeignKey("IdInstructor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Helluz.Models.Inscripcion", b =>
                {
                    b.HasOne("Helluz.Models.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helluz.Models.Membresia", "Membresia")
                        .WithMany("Inscripcion")
                        .HasForeignKey("IdMembresia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("Helluz.Models.Instructor", b =>
                {
                    b.HasOne("Helluz.Models.Usuario", "Usuario")
                        .WithOne("Instructor")
                        .HasForeignKey("Helluz.Models.Instructor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Helluz.Models.Alumno", b =>
                {
                    b.Navigation("Asistencia_Alumnos");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Helluz.Models.Disciplina", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Helluz.Models.Horario", b =>
                {
                    b.Navigation("AlumnoHorarios");

                    b.Navigation("AsistenciaInstructors");
                });

            modelBuilder.Entity("Helluz.Models.Instructor", b =>
                {
                    b.Navigation("AsistenciaInstructors");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Helluz.Models.Membresia", b =>
                {
                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("Helluz.Models.Usuario", b =>
                {
                    b.Navigation("Instructor");
                });
#pragma warning restore 612, 618
        }
    }
}
